/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Returns streaming chat responses */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        threadId: string;
                        model: string;
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Chat response stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number | null;
                    cursor?: number | null;
                };
                header?: never;
                path: {
                    threadId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            messages: {
                                message: {
                                    messageId: string;
                                    threadId: string;
                                    parentId: string | null;
                                    content: string;
                                    /** @enum {string} */
                                    role: "user" | "assistant";
                                    model: string;
                                    /** Format: date-time */
                                    createdAt: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                };
                                movies: {
                                    messageId: string;
                                    movieId: string;
                                    title: string;
                                    releaseYear: string;
                                    why: string;
                                    /** Format: date-time */
                                    createdAt: string;
                                    movie: {
                                        movieId: string;
                                        tmdbId: number;
                                        title: string;
                                        /** Format: date-time */
                                        releaseDate: string;
                                        posterPath: string;
                                        backdropPath: string;
                                        /** Format: date-time */
                                        createdAt: string;
                                    };
                                }[];
                            }[];
                            nextCursor: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
