export {default as RegisterPage} from './RegisterPage'
export {default as LoginPage} from './LoginPage'
export {default as MoviesPage} from './MoviesPage'
export {default as MovieDetailPage} from './MovieDetailPage'
export {default as SeenPage} from './SeenPage'
export {default as WatchlistPage} from './WatchlistPage'
export {default as SearchPage} from './SearchPage'
export {default as FavoriteMovies} from './FavoriteMovies'