services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
