import type { Metadata } from 'next';
import { Schibsted_Grotesk } from 'next/font/google';

import './globals.css';

import { cn } from '@/lib/utils/cn';
import { QueryClientProvider } from '@/providers/query-client-provider';
import { UserProvider } from '@/providers/user-provider';
import { NavView } from '@/components/nav/nav-view';

const fontSans = Schibsted_Grotesk({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'FILMLIST',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('bg-surface-0 text-text-primary', fontSans.className)}>
        <QueryClientProvider>
          <UserProvider userId="j575fwxmyt948vvpf9ppwd6dkx7h7se8" anon={true}>
            <div className="grid h-screen grid-cols-[260px_1fr]">
              <NavView />
              <main className="bg-surface-0 w-full">{children}</main>
            </div>
          </UserProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
