import type { Metadata } from 'next';

import { TRPCProvider } from '@/lib/trpc/provider';
import { ConvexClientProvider } from '@/providers/ConvexClientProvider';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClientProvider>
      <TRPCProvider>
        <html lang="en">
          <body className={`antialiased`}>{children}</body>
        </html>
      </TRPCProvider>
    </ConvexClientProvider>
  );
}
