"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const trpc_server_1 = require("@hono/trpc-server");
const hono_1 = require("hono");
const cors_1 = require("hono/cors");
const app_router_1 = require("./app.router");
const app = new hono_1.Hono();
app.use((0, cors_1.cors)({ origin: 'http://localhost:5173' }));
app.use('/api/*', (0, trpc_server_1.trpcServer)({ router: app_router_1.appRouter }));
exports.default = app;
